---
- name: pre_k3s | Disable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  failed_when: false
  # notify:
  #   - Reboot
  loop: "{{ awx_on_k3s_disable_services }}"

# Cannot reboot when running against localhost but in the future could be run from other system
# - name: pre_k3s | Flush handlers
#   ansible.builtin.meta: flush_handlers

- name: pre_k3s | Ensure required packages are installed
  ansible.builtin.package:
    name:
      - git
      - curl
    state: present

- name: pre_k3s | Ensure python packages are installed
  ansible.builtin.pip:
    name:
      - cryptography
      - kubernetes
      - kubernetes-validate
    state: present
...
